name = "alhamed-store"
main = ".open-next/worker.js"
compatibility_date = "2026-08-16"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "alhamed-store"

[images]
binding = "IMAGES"

[vars]
NEXT_PUBLIC_SITE_URL = "https://alhamed-store.workers.dev"
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin123"
